define([], function () {
  return {
    PropertyPaneDescription: "Configure the SOP Repository web part.",
    DataGroupName: "Data Sources",
    DisplayGroupName: "Display Options",
    SopSiteUrlLabel: "SOP Site URL",
    LibraryNameLabel: "Document Library Name",
    ProcessListNameLabel: "Process List Name",
    RolesListNameLabel: "Roles List Name",
    ShowGapsLabel: "Show Gap Processes",
    DefaultRoleLabel: "Default Role Override",
    LoadingLabel: "Loading SOP data...",
    ErrorLabel: "Error loading data",
    NoRoleDetectedLabel: "Could not detect your role. Please select a role below.",
    SelectRoleLabel: "Select a role",
    DocumentedSectionTitle: "DOCUMENTED",
    GapsSectionTitle: "GAPS — No SOP Yet",
    SearchPlaceholder: "Search processes...",
    StatusApproved: "Approved",
    StatusDraft: "Draft",
    ReviewDateLabel: "Review Date",
    NoDocumentsLabel: "No documented processes found for this role.",
    NoGapsLabel: "All processes are documented for this role.",
  };
});
